debug: true
server:
  host: "0.0.0.0"
  port: "9300"

redis:
  host: "192.168.100.233"
  port: "6380"
  passwd: "56grTbvMYaOQ"
  dbnum: 14

mongodb:
  host: "192.168.100.233"
  port: "27020"
  user: "test"
  passwd: "test"
  database: "testrole"