debug: true
server:
  host: "0.0.0.0"
  port: "9300"

redis:
  host: "127.0.0.1"
  port: "6379"
  passwd: ""
  dbnum: 10

mongodb:
  host: "47.99.56.228"
  port: "27017"
  user: "root"
  passwd: "123456"
  database: "testrole"